-- Deprecated: do not use this file for new environments.
--
-- Source-of-truth bootstrap scripts:
--   - scripts/init-prod-db.sql  -> production-safe schema with required departments only
--   - scripts/init-dev-db.sql   -> local development schema with demo users and sample inventory
--
-- This compatibility placeholder remains in the repository so older references fail safely
-- instead of provisioning an outdated schema.
