-- Deprecated legacy migration helper.
--
-- The current schema already defines requisitions.item_id as VARCHAR(50).
-- For new environments, use:
--   - scripts/init-prod-db.sql
--   - scripts/init-dev-db.sql
--
-- This file is intentionally a no-op placeholder.
