-- Deprecated legacy migration helper.
--
-- The current requisitions schema and indexes are defined in:
--   - scripts/init-prod-db.sql
--   - scripts/init-dev-db.sql
--
-- This file is intentionally a no-op placeholder.
